// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQu10Jhvg6qkndJnULasdA4mktLITND-8',
    appId: '1:416125735679:web:39a9950f5c2468dda3f2ca',
    messagingSenderId: '416125735679',
    projectId: 'event-booking-app-a4833',
    authDomain: 'event-booking-app-a4833.firebaseapp.com',
    storageBucket: 'event-booking-app-a4833.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxA8zB3VlyGAwYg0UOzBMWdrF8iWir50',
    appId: '1:416125735679:android:9a71125179c27022a3f2ca',
    messagingSenderId: '416125735679',
    projectId: 'event-booking-app-a4833',
    storageBucket: 'event-booking-app-a4833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJ92d7wd_gepAgJKqLd_oXmNE7x_yOVc',
    appId: '1:416125735679:ios:afe54c4f416bf0c7a3f2ca',
    messagingSenderId: '416125735679',
    projectId: 'event-booking-app-a4833',
    storageBucket: 'event-booking-app-a4833.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJ92d7wd_gepAgJKqLd_oXmNE7x_yOVc',
    appId: '1:416125735679:ios:afe54c4f416bf0c7a3f2ca',
    messagingSenderId: '416125735679',
    projectId: 'event-booking-app-a4833',
    storageBucket: 'event-booking-app-a4833.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQu10Jhvg6qkndJnULasdA4mktLITND-8',
    appId: '1:416125735679:web:8165fefb6f6c682ba3f2ca',
    messagingSenderId: '416125735679',
    projectId: 'event-booking-app-a4833',
    authDomain: 'event-booking-app-a4833.firebaseapp.com',
    storageBucket: 'event-booking-app-a4833.firebasestorage.app',
  );
}
